# Use root/example as user/password credentials
version: '3.1'

services:

  frontend:
    image: frontend
    ports:
      - 3000
    networks:
      - front-tier
      - back-tier

  backend:
    image: backend
    ports:
      - 8080
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    depends_on:
      - mongo
    networks:
      - front-tier
      - back-tier

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
      - 28017:28017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-data:/data/db
    networks:
      - back-tier

  lbweb:
    image: dockercloud/haproxy
    ports:
      - 3000:80
      - 1936:1936
    links:
      - frontend
    networks:
      - front-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  lbapi:
    image: dockercloud/haproxy
    ports:
      - 8080:80
      - 1937:1936
    links:
      - backend
    networks:
      - back-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge